version: "3.9"

services:
  app:
    container_name: node-app
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - 8000:8000
  
  exporter:
    container_name: prometheus-exporter
    build:
      context: .
      dockerfile: exporter/Dockerfile
    environment:
      - POLLING_INTERVAL_SECONDS=5
      - EXPORTER_PORT=9877
      - TARGET_HOST=node-app
      - TARGET_PORT=8000
      - TARGET_METRICS=status
    ports:
      - 9877:9877
  
  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/config.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
