# prometheus configs
global:
  scrape_interval: 5s
  scrape_timeout: 5s

# scrape configs
scrape_configs:
  - job_name: "python-exporter"
    metrics_path: /
    static_configs:
      - targets: ["host.docker.internal:9877"] # config on node-app container
